namespace Art
{
	constexpr auto Deamon{
		"                         _.---.\n"
		"                       .' :.--.\"-.\n"
		"                     .'.-\";.--.`. \\\n"
		"                   .'.' :\\:-./;`.  ;                  ;\n"
		"                .-\" / .-'-   -';   :                 /\n"
		"               (/   .:: ._  _. :\\ \\;;              .'\n"
		"               :  .'j ;'._` _.`: ;/ :             :\n"
		" \\             ; / : `;        :':  :`-           ;\n"
		"  \"-.          ::   \\ :\\  s   /; ;   \\            :\n"
		"     `.       / ; ;  `.\\  ==  / /:\\ \\ `._          \\\n"
		"       \\     :  : :   ;\\`.__.' : ; `.`.; `          ;\n"
		" \"-.    ;    ;. ; ;  /  ;\\  ;   \\: \\ `(            /:\n"
		"    `.  :  `-: \" / .'   : \\      )\\ \"--`._.      .' ;\n"
		"      \\ ;   (;  / /   .';`     .(  \"-.___;.     /  /\n"
		"       y     :-' :   / /      (  `.( __.-' \\   : .'\n"
		"    .-\"    .t \\  ;  :-(        `-. `\"-.)    ;  ;/       .-\n"
		"  .'     .'  \\ :-: :              \\ \"-.`.   :  :       (\n"
		" /     .'     \\;  t.\\        :     `.  ) ;  :   \\       `-\n"
		"      :  _     ;  : `      : ;       )/ /   ;    \"-.\n"
		"      :.'/ /\"l :  ;(o)     ; :    (o)^-:    ;       \"\"--..\n"
		"      ' / /  :/ ; '.      /   \\      / ;    ;     .-\"\n"
		" \\     : :      :   ;----'     `----'  ;    ;    /\n"
		"  ;  / ; ;       ;  ;     .'  `.       ;    ;_.-\"\n"
		"  : :  : :       :  :        ;  \\      ;    ;            /\n"
		"  ; ;   \\ \\       ;  ;       :        /    :           .'\n"
		" /  :    `.`.     :  :       ;       :     ;        .-\"/\n"
		"     \\     `.\"-.   ; :               ;    /      .-\" .'\n"
		"      `--.   \"-.\"-.: ;  :    c    ; :    /      /  .'\n"
		"         :      \"-.\"t.  ;         : ;   /      :  (\n"
		"          \\        j+.\"-.         ;/   /-.      \\  \\\n"
		"    \"-.    \"-.    /  \\\"-.\"-.      /   /   `,     ;  ;\n"
		"       `.     `. :    \\  \"-.`..-./   /\\     \\   /   :\n"
		"         \\      \\;     t.  .`;-' `  /  ;      .'    ;\n"
		"          ;     :       \\`-;\":---  ;   :    .'     /\n"
		"          :     ;        ;  \"-`+-+'    :  .'     .'\n"
		"          ;    :         :     ; ;      \\/      /\n"
		"\"-.      :     :          ;   / /        \\     :\n"
		"_  \\     ;     ;          :_.'.'          \\    ;\n"
		" \"-.;   :      ;          :`-';            \\   :\n"
		"    :   ;\\     ;          :>  :             ;   \\\n"
		"     \\  : `.   ;          :>   ;            :    `-     .'\n"
		"         \\  \"-.;          :>   :             ;        ./\n"
		"          `._.-;          ;     \\            :      .':\n"
		" \"-.           ;          ; bug  \\            ;    /  ;\n"
		"    \\_..---..  ;         :_       \\           :._.'  :\n"
		" `.  \"-.     \"-:         ; \"-.  .-\"`.          ;     ;\n"
		"   \\    `-._.._:        :     `.     `.        :    /    _\n"
		"    \"-.        \"\"---..__;-.     \\      `.     . ; .'  .-\"\n"
		"       \"\"--..            \"-;     ;    .-\"\"\"-.  \"\"\"   /\n"
		"             \"-.            `.   :           `-.___.'\n"
	};

	constexpr auto Win{
		"                             . ...\n"
		"                         .''.' .    '.\n"
		"                    . '' \".'.:I:.'..  '.\n"
		"                  .'.:.:..,,:II:'.'.'.. '.\n"
		"                .':.'.:.:I:.:II:'.'.'.'.. '.\n"
		"              .'.'.'.'::.:.:.:I:'.'.'.'. .  '\n"
		"             ..'.'.'.:.:I::.:II:.'..'.'..    .\n"
		"            ..'.'':.:.::.:.::II::.'.'.'.'..   .\n"
		"           ..'.'.'.:.::. .:::II:..'.'.'.'.'.   .\n"
		"          .':.''.':'.'.'.:.:I:'.'.'.'.'.. '..  ..\n"
		"          ':. '.':'. ..:.::.::.:.'..'  ':.'.'.. ..\n"
		"         .:.:.':'.   '.:':I:.:.. .'.'.  ': .'.. . ..\n"
		"         '..:.:'.   .:.II:.:..   . .:.'. '.. '. .  ..\n"
		"        .. :.:.'.  .:.:I:.:. .  . ..:..:. :..':. .  '.\n"
		"       .:. :.:.   .:.:I:.:. .    . ..:I::. :: ::  .. ..\n"
		"       .. :'.'.:. .:.:I:'.        ..:.:I:. :: ::.   . '.\n"
		"       '..:. .:.. .:II:'         ,,;IIIH.  ::. ':.      .\n"
		"      .:.::'.:::..:.AII;,      .::\",,  :I .::. ':.       .\n"
		"      :..:'.:II:.:I:  ,,;'   ' .;:FBT\"X:: ..:.. ':.    . .\n"
		"     .. :':III:. :.:A\"PBF;.  . .P,IP;;\":: :I:..'::. .    ..\n"
		"     . .:.:II: A.'.';,PP:\" .  . ..'..' .: :.::. ':...  . ..\n"
		"     . .: .:IIIH:.   ' '.' .  ... .    .:. :.:.. :...    .'\n"
		"     . .I.::I:IIA.        ..   ...    ..::.'.'.'.: ..  . .\n"
		"      .:II.'.':IA:.      ..    ..:.  . .:.: .''.'  ..  . .\n"
		"     ..::I:,'.'::A:.  . .:'-, .-.:..  .:.::AA.. ..:.' .. .\n"
		"      ':II:I:.  ':A:. ..:'   ''.. . : ..:::AHI: ..:..'.'.\n"
		"     .':III.::.   'II:.:.,,;;;:::::\". .:::AHV:: .::'' ..\n"
		"     ..\":IIHI::. .  \"I:..\":;,,,,;;\". . .:AII:: :.:'  . .\n"
		"     . . IIHHI:..'.'.'V::. \":;;;\"   ...:AIIV:'.:.'  .. .\n"
		"      . . :IIHI:. .:.:.V:.   ' ' . ...:HI:' .:: :. .  ..\n"
		"      . .  ':IHII:: ::.IA..      .. .A .,,:::' .:.    .\n"
		"      :.  ...'I:I:.: .,AHHA, . .'..AHIV::' . .  :     ..\n"
		"      :. '.::::II:.I:.HIHHIHHHHHIHHIHV:'..:. .I.':. ..  '.\n"
		"   . . .. '':::I:'.::IHHHHHHHHMHMHIHI. '.'.:IHI..  '  '  '.\n"
		"    ':... .  ''\" .::'.HMHI:HHHHMHHIHI. :IIHHII:. . . .    .\n"
		"     :.:.. . ..::.' .IV\".:I:IIIHIHHIH. .:IHI::'.': '..  .  .\n"
		"   . .:.:: .. ::'.'.'..':.::I:I:IHHHIA.'.II.:...:' .' ... . '..\n"
		"  '..::::' ...::'.IIHII:: .:.:..:..:III:.'::' .'    .    ..  . .\n"
		"  '::.:' .''     .. :IIHI:.:.. ..: . .:I:\"' ...:.:.  ..    .. ..\n"
		"     .:..::I:.  . . . .IHII:.:'   .. ..\".::.:II:.:. .  ...   . ..\n"
		"  .. . .::.:.,,...-::II:.:'    . ...... . .. .:II:.::  ...  .. ..\n"
		"   ..:.::.I .    . . .. .:. .... ...:.. . . ..:.::.   :..   . ..\n"
		"    .'.::I:.      . .. ..:.... . ..... .. . ..::. .. .I:. ..' .\n"
		"  .'':.: I.       . .. ..:.. .  . .. ..... .:. .:.. .:I.'.''..\n"
		"  . .:::I:.       . . .. .:. .    .. ..  . ... .:.'.'I'  .  ...\n"
		"  . ::.:I:..     . . . ....:. . .   .... ..   .:...:.:.:. ''.''\n"
		"  '.'::'I:.       . .. ....:. .     .. . ..  ..'  .'.:..:..    '\n"
		"        :. .     . .. .. .:.... .  .  .... ...   .  .:.:.:..    '.\n"
		"        :.      .  . . .. .:.... . . ........       .:.:.::. .    .\n"
		"        :. .     . . . . .. .::..:  . ..:.. .        ::.:.:.. .    .\n"
		"        :.. .    . . .  . .. ..:.:  .. .. .:. ..     ':::.::.:. .   .\n"
		"        ':.. .  . . . .. .. ...::' .. ..  . .:. .     V:I:::::.. .   :.\n"
		"         ::. .  . .. .. ... .:.::  .. .  . .. .. .     VI:I:::::..   ''B\n"
		"          :.. .   . .. ..:.. ..I:... . .  . .. ... .    VII:I:I:::. .'::\n"
		"          ':.. . . . .. ..:..:.:I:.:. .  . .. . .:. .    VHIII:I::.:..':\n"
		"           ::..   . . .. ..:..:.HI:. .      . . .... .   :HHIHIII:I::..:\n"
		"           ':. .  . .. .. ..:.:.:HI:.    . . .. ..... .   HHHHIHII:I::.'\n"
		"            :.. .  . . .. .:.:.:.HI:.      . . .. ... .   IHHHHIHHIHI:'\n"
		"             :..  .  . . .. ..:..IH:.     . . .. .. ,,, . 'HHHHHHHHI:'\n"
		"             ':..   . . .. ..:.:.:HI..   .  . .. . :::::.  MIH:\"\"\"'\n"
		"              :. . .  . .. ..::.:.VI:.     . . .. .:::'::. HIH\n"
		"               :..  .  . .. .:.:.:.V:.    . . . ...::I\"A:. HHV\n"
		"                :. .  .  . .. ..:.:.V:.     . . ....::I::'.HV:\n"
		"                 :. .  . . . .. .:..II:.  . . . ....':::' AV.'\n"
		"                  :.. . . .. ... .:..VI:. . . .. .:. ..:.AV'.\n"
		"                  ':.. . .  .. ..:.:.:HAI:.:...:.:.:.:.AII:.\n"
		"                   I:. .  .. ... .:.:.VHHII:..:.:..:A:'.:..\n"
		"                   IA..  . . .. ..:.:.:VHHHHIHIHHIHI:'.::.\n"
		"                   'HA:.  . . .. ..:.:.:HHHIHIHHHIHI:..:.\n"
		"                    HIA: .  . . .. ...:.VHHHIHIIHI::.:...\n"
		"                    HIHI:. .  .. ... .::.HHHIIHIIHI:::..\n"
		"                    HII:.:.  .  .. ... .::VHHIHI:I::.:..\n"
		"                    AI:..:..  .  . .. ..:.VHIII:I::.:. .\n"
		"                   AI:. ..:..  .  . .. ..' VHIII:I;... .\n"
		"                  AI:. .  .:.. .  .  . ...  VHIII::... .\n"
		"                .A:. .      :.. .  . .. .:.. VHII::..  .\n"
		"               A:. . .       ::. .. .. . .:.. \"VHI::.. .\n"
		"             .:.. .  .        :.. .:..... .::.. VHI:..\n"
		"            ... . .  .     . . :.:. ..:. . .::.. VI:..  .\n"
		"           .. .. .  .    . . ...:... . .. . .:::. V:..  .\n"
		"          '.. ..  .   .  .. ..:::.... .:. . ..::.. V..  .\n"
		"        . . .. . .   . . .. ..:::A. ..:. . . .::.. :..\n"
		"       . .. .. .. . .  . ... ..::IA.. .. . .  ..::. :..  .\n"
		"      .. .. ... . .  .. .... .:.::IA. . .. . ..:.::. :.  .\n"
		"     . . . .. .   . . .. ..:..:.::IIA. . .  .. .:.::. :. .\n"
		"    .. . .  .   . . .. ... ..:.::I:IHA. .  . . ..:.::. . .\n"
		"   .: ..  .  .   . . ... .:.. .:I:IIHHA. .  . .. .::I:. .\n"
		"  .::.  .     . . .. ..:. .::.:IIHIIHHHA.  .  .. ..:I:. . .\n"
		"  A::..      .  .  ...:..:.::I:IHIHIHHHHA.  .  . ..::I:. .\n"
		" :HI:.. .       . .. .:.:.::I:IHIHIIHIHHHA. .   .. .::I:. ..\n"
		" AI:.. .. .    . .. .:.:.::II:IHIIIHIHIHHHA.  .  . ..::I:. ..\n"
		":HI:.. . .   .  . .. .::.:I:IHIHIIIHIHIIHHHA..  . .. .::I:. ..\n"
		"AI:.:.. .  .  .  ... .::.::I:IHIIHIHIHIHIHIHHA. .  . ..::I:. .\n"
		"HI:. .. . .  .  . .. .:..::IIHIHIHIIIIWHIIHHMWA.  . . .:::I:. . .\n"
		"HI:.. . .  .   . .. ..:.::I:IIHHIIHIHIHIHHMMW\"  '.. . ..:::II: . .\n"
		"HI::.. .  .   .  .. .:..:::IIHIHIIWIWIIWMWW\" .    .. . ..::III: .  .\n"
		"HI::... . . .  . ... ..:.:::IIHIWIWIWMWMWW. .  .   . .. .:.:III. .   .\n"
		"II::.:.. . .  .  .. ......:..IHWHIWWMWMW\".. . . . . '... .:.:IHI:..    .\n"
		"II:I::.. .  .   .  . .....::.:IHWMWWWMW:.. .  .  . .  .:..:::IIHII..\n"
		":II:.:.:.. .  .   . ......:.:.:IWWMWWW:.:.. .  .  .  . :...:.:IHHI:..\n"
		" HI::.:. . . .  .  . ...:.::.::.VWMWW::.:.:.. .  . .. . :.. ..:IHHI::.'-\n"
		" HII::.:.. .  .  . .. .:..:.'.  'WWWI::.::.:.. . .  . .. ':...:II:IIII::\n"
		" III::.:... .  .  . ...:.:... .   WII:I::.:.. .  .  .. . . :.:::...::.::\n"
		"  VII::.:.. . . . .. ...:....      VHI:I::.:.. .  . ... .. .::.:..:.:..:\n"
		"   VII::.:.. . .  . ..:.::.. .     :HHII:I::.:.. . . .. ..  .'::':......\n"
		"   III:I::.. .. . . .. .:.:.. .    :VHIHI:I::.:... . . .. .. .':. .. .AH\n"
		"  AA:II:I::.. . . .  .. ..:.. . .  ::HHIHII:I::.:... .. .. ... .:.::AHHH\n"
		" AHH:I:I::.:.. .  . .. ..:.:.. .   ::VHHHVHI:I::.:.:.. ..:. .::.A:.AHHHM\n"
		" HHHAII:I::.:.. . . . .. ..:.. . . :::HIHIHIHII:I::.:.. .. .:. ..AHHMMM:\n"
		"AHHHH:II:I::.:.. . . .. ..:.:.. . .:I:MMIHHHIHII:I:::.:. ..:.:.AHHHMMM:M\n"
		"HHHHHA:II:I::.. .. . . .. .:... . .:IIVMMMHIHHHIHII:I::. . .. AHHMMMM:MH\n"
		"HHHHHHA:I:I:::.. . . . ... ..:.. ..:IHIVMMHHHHIHHHIHI:I::. . AHMMMMM:HHH\n"
		"HHHHHMM:I::.:.. . . . .. ...:.:...:IIHHIMMHHHII:.:IHII::.  AHMMMMMM:HHHH\n"
		"HHHHHMMA:I:.:.:.. . . . .. ..:.:..:IIHHIMMMHHII:...:::.:.AHMMMMMMM:HHHHH\n"
		"HHHHHMMMA:I::... . . . . .. ..:.::.:IHHHIMMMHI:.:.. .::AHMMMMMMM:HHHHHHH\n"
		"VHHHHMMMMA:I::.. . .  . . .. .:.::I:IHHHIMMMMHI:.. . AHMMMMMMMM:HHHHHHHH\n"
		" HHHMMMMMM:I:.:.. . .  . . ...:.:IIHIHHHIMMMMMHI:.AHMMMMMMMMM:HHHHHHHHHH\n"
		" HHHHMMMMMA:I:.:.. .  .  . .. .:IIHIHHHHIMMMMMH:AMMMMMMMMMMM:HHHHHHHHHHH\n"
		" VHHHMMMMMMA:I:::.:. . . . .. .:IHIHHHHHIMMMV\"AMMMMMMMMMMMM:HHHHHHHHHHHH\n"
		"  HHHHHMMMMMA:I::.. .. .  . ...:.:IHHHHHHIM\"AMMMMMMMMMMMM:HHHHHHHHHHHHHH\n"
		"  VHHHHHMMMMMA:I:.:.. . . .  .. .:IHIHHHHI:AMMMMMMMMMMMIHHHHHHHHHHHHHHHH\n"
		"   VHHHHHMMMMMA:I::.:. . .  .. .:.:IHHHV:MMMMMIMMMMMMMMMMMMMHHHHHHHHV::.\n"
		"    VHHHHMMMMMMA:::.:..:.. . .. .:::AMMMMMMMM:IIIIIHHHHHHHHHHHHHHHV:::..\n"
		"     HHHHHMMMIIIA:I::.:.:..:... AMMMMMMMMMM:IIIIIIHHHHHHHHHHHHHHHV::::::\n"
		"     VHHHHMMIIIIMA:I::::.::..AMMMMMMMMMMM:IIIIIIIHHHHHHHHHHHHHHV::::::::\n"
		"      HHHHMIIIIMMMA:II:I::AIIIMMMMMMMMMM:IIIIIIIHHHHHHHHHHHHHHV:::::::::\n"
		"      VHHHHIIIMMMMMMA:I:AIIIIIIMMMMMM:IIIIIIIIHHHHHHHHHHHHHHV::::::::\"'\n"
		"       HHHHHIIMMMMMMIMAAIIIIIIIIMMM:IIIIIIIIHHHHHHHHHHHHHHHV:::::\"\"'\n"
		"       VHHHIIIIMMMMIIIIIIIIIIIIII:IIIIIIIIHHHHHHHHHHHHHHHV::\"\"'\n"
		"        VHHIIIMMMMMIIIIIIIIIIIIIIIIIIIIIHHHHHHHHHHHHHHHV\n"
		"         VHHIMMMMMMMIIIIIIIIIIIIIIIIIHHHHHHHHHHHHHV\n"
		"          VHHHMMMMMMMMIIIIIIIIIIIHHHHHHHHHHHV\n"
		"           VHHHMMMMMMMMMMMMMHHHHHHHHHHHHHV\n"
	};

	constexpr auto Start{
		"                                                                       _.-'`\"=-+`\";.\n"
		"                                                                        _.- `   _/ :.\n"
		"                                                                  -'`         .=+\"'*+._ \n"
		"                                                                           .;\":``     `\"\"+=.\n"
		"                                                                      __.+'::`             \"+\n"
		"                                                                 _.+`\"   `'::.-+`            \".\n"
		"                                                            .--+\"`        .:\"  `\"+            +.\n"
		"                               '.   _.---.            __.+`\"`.          .:^     `\";;+'       \":;\n"
		"         .--'` `                  `\"`*+.   \\:`'\"+._.n:\"    '`____. ,.  ' /   __    +.+'        ;:\n"
		"  _ _.-'`                     `-+'+::+~`'\"`\"-:`-+:.   ___.--`_+;;+?`     ; '`  ` /\".=.:.      f:\n"
		"                                              `\"` `\":.___.--`;. ..`     /  ,.-  ..:/  ;:`     .:\n"
		"                                                             :: :`     /      .=`:/) /      .:;\"\n"
		"                             .--.                            `. ;      -,      .'\"`           ;\n"
		"                           .:_.--+-.          ` --._____       `;:.     '_        ,m   .-\"  .;`\n"
		"               ___    _.--'.--\"` '.  .            _.+\"` _\"`-.    ;       \"'     _+dMM:` /  .;`\\\n"
		"        .--'`    `'\"-.,__.--.      : :          .' ._+\"`     \"-..\"-.     ;  _.`\".\"P\" _.- .:`. \"*+._\n"
		"      .'                     +_.-:/  /          :`.+`       .---:`\"-._    `'   .-\"     ./ .:`.:   `:;\n"
		"     /                       __ _:  ;           ';`-.     .'       _.-`\"`+---,-`    _.-\"/:.      .::+\"\n"
		"                      .--'`'`  `-._'.\\          __+.___.--:__  .-`         _.-+  \"`-._.-m::  /  ':.\\\n"
		"                 __.-` __.-`\"        `+-._.-+\"\"`--\"               _.' _.cmf`        `+::\"_.+; .:::+\"\n"
		"              .-\"` --\"`       .                               .\"`    _dM\"YMMb          \\  `\"m.:::.\n"
		"            /` .-^- --+. ``'-._'.                        .--/   _.mfMMNb.`\"WI.             .'M / /  \n"
		"         .-``./        `;.     _.'.-.               _.-`__.`_.-``\"*+m YMb.`MMI.       ;`\"   I`-.\n"
		"        /              .\"_ __.'<'   `-.   ___. --'`_.=+` .-`       `Yb MMb: lM:             d'  ;\n"
		"                  _.-'    .'   '.`.     `\"'--=====\"`  .-'           `+Y,\"Mb.YMM. _.-`        d  -'\n"
		"             .-\"`       .+_    .' ;             /  .-`                f+YMmf+*\"\"\"`          i\" \n"
		" .-\"`-.     /       _.-'.-'`-./_.'             +-           .      .`**\"`*\"`             .i\"\n"
		"       )    .-\"` `\"\"-.____.-\"`              .-'          _.\"  _.-'                   _.m\"`\n"
		"       '._.'                             .-\"b.          .\"-+=\"`                   ,m+\"`\n"
		"                                    _.i::  `\".       _.-\"` /                  .d\"`\n"
		"                                 _.dW;:YWb.   '-. .-`:    ;                d\"`\n"
		"                               .' `\"YM;:YWWm. _.    /    .b.            :I\"\n"
		"                             .'     `WWn:WP*\"`|    ;    pI Am._       .mMM._.\n"
		"                            :      .-`\"*\"     :        :MA.\"WWMbm+._.iMmMMMM:\n"
		"                            :    .:/         .dSSSSb  .:MMMm.`**YMMMM.dMMMMMMf ._\n"
		"                           _;   ` '          `:`   \\ `*'WMMMMAm..\"YY\".mMMmdMMMmMMP\"\n"
		"                          / `                 \\     ; `fMMMMMMMMMmMMMMSMMMMMM+\"Ym\n"
		"                       .-;   __.'              ;    `  .mSSs.WMMMMSMSMSMmMMMMM*\\ \"`\n"
		"                       _<+ .+                 /   .`  dRSSSP\"*+FMMMMMMMFf*MMP`  :\n"
		"                        .\"-/                 ,   +__.dRRSSP ;    `'\"\"\"`'\"\"       `\n"
		"                                    ._ ,_-`'-ssSRRRRPmSSP` /      .'\n"
		"                                   . ,`' `'.::.`\"+SSRRRP\".:         _.`  /        |\n"
		"                                   ::'  _`  `;:::..,.,.;:;`     _.-'__.-`         ;\n"
		"                                  `;,:;`  ,           .' :  _.-``\"`       \n"
		"                                    -:;-`.;:.  ,-:,:::/  /-`              /       .\n"
		"                                       ':/`-;` `\" `;:/  ;:::`       __..-'       /\n"
		"                                      _.'         .-'   :::`    _.-'           .;\n"
		"                                   .-'         .-'      ;:` .-\"`           _.=\"|\n"
		"                                .-'.    .-'_.'`         ::.'`            .=\"`` ;      zi.\n"
		"                             .-'.-'    /s;Y\"`           ;/           .=\"`      `\n"
		"                       _ -=\"`         /S\"`              /        .-\"`           .\n"
		"                   `\"- ---=;`>;.  ;  ;P`               ;       /\"`\n"
		"                     `\"'--_;->;:'   ./`                        :    \n"
		"                    ---._ -~_;;;.:./\"`                          '  \n"
		"             .----._-.__.`\"'`:;;;;\"                   \n"
		"                    `\"'\"-._-\"\";;-`  \n"
		"                         _.-`\"\n"
		"                         _.-`\"\n"
	};

	constexpr auto Glitch{
		"           .:IIIIHIHHIHHHII::I:.\n"
		"         .IIIIHIHHHHHHIHIIIIMHHI:,\n"
		"       :IIIIHIHHHHHHMMHHIHHIIHHIII:.\n"
		"     .:IHIHHHHHHHHHHHHHIHIHHIHHHIH:I:,\n"
		"    ,.:HIHHHHHHHHHHHHHHHHHHHHHIHIHHII:.\n"
		"   ,.:IHHHHHHHHHHMMMMHHHHHHHIIHHHIHIII,\n"
		"  .:IIHHHHHHHHMMMMMHHHHMMMHHMHHHIIIHIIII:\n"
		"  .IIHHHMMMMMMMHHMMMHHHMMMHHMHII:HHHII:I.\n"
		"  :HIHHHMHMMMMMMMMMMMMHMHHHHII:HHMMHII:II\n"
		" :HHHHMHMMMMMMMMMMMMMMMHIIHIHHMMHHHHII::I:\n"
		":IIHHHHHMHMMMMMMMMMMHMMHIHMMMMHHHI:\"::IIHII:\n"
		":IHHHHHMHMMMMMMMMMMMMHHI:II::I:\"' .   '\"IHH.\n"
		"::HHHHMHMMMMMMMMMMHMHHI:II::.'  .       'VMA.\n"
		"IHHHHHMHNMMMMMMMMHMHHI:II:. . .          \"MMH.\n"
		"HHHHHMHMMMMMMMMMMHMHI:I::.' .  . .      .,MMM:.\n"
		"HHHHMHMMMMMMMMMMMHMHI:II:. ..  .    ..LI:\"IMMI.\n"
		"HMHMMMMMMMMMMMMMMHMHI:II.'.        :HT;.,, VHI:\n"
		"HHHHHMHMMMMMMMMMHMHHHI:HMHII:,.   ':,MHP\"HPIHII.\n"
		"IHHHHMHMMMMMMMMMHMHHHII::IT:.I:.  'HMMH ,:\" VII:\n"
		":HHHHHHHMHMMMMMHMHHHHIIMMMPVHI::. .P\"TIT\"'  IH:I\n"
		"HHIHHHHHHMHMMMMHMHHHHH:VMMM:.HI:H:. :. . . .II:I.\n"
		":HHHHHMHMMMMMHMHHHHIIHMMHHI:.:HI:. . .. .   :III;\n"
		"IHHHHMHMMMMMMMHHHHHI:IT:TI:..:HI:.. ..:. .  :IHII\n"
		" IHHMHMMMMMMMMMMMHHI:I::.:. ..:II::.. :I..  :HIIH.\n"
		" 'HHHMHMMMMMHMHHHH:II:.. ...:II:II./'::.  ' IHHIH;\n"
		"  HHMHMMMMMMMHMHHHH:I:I::....::VIHI;, ' . . IHHIHA\n"
		"  MHHMMMMMMMMMHMHHH:II:::...::II:::.;,,,:   AHHIHH;\n"
		"  ;HHMHMMMMMMMMHMHH-:II::..:::I::\"\",,:\"''  .HHHIHHI.\n"
		"  'HHHMHMMMMMMMMHMHHA:II:.:H.::-\"'\"\"' ,'. .AMHHIHHH;\n"
		"   :HHMHMMMMMMMMMMHMHA:II::.::::-;,,:: .. :AMHI:IHHI\n"
		"   'HHMHMMMMMMMMMMHMHHA:III:::II:II::. . .AMMHI:IHHH.\n"
		"    :HHHMHMMMMMMMMMHMHHA:IIIHII:.:::. . .AMMMHI:IHHH:.\n"
		"    'HHMHMMMMMMMMMMMMHMHHHI:\":VIII::...:AMMMMHHI:IHHHI\n"
		"     ;IHMHMMMMMMMMMMMMMHMHHII:. '\"\" 'AMMMMMMMHI:IIHHH:I.\n"
		"     :IMHMMMMMMMMMMMMMMHMHHHII:.  .:IHMMMMMMHHHIHIHHHI::.\n"
		"     ;HHHMHMMMMMMMMMMMMMMHMHHHI:..IHHMHMMHHHHHIHHHMHH;I:\".'\n"
		"     ;HHHHHMHMMMMMNMMMMMMMHMHHHI::.HHHHMMHHHHHIHIHHHHHI:'\n"
		"     :HHHHHHHHMHMMMMMMMMMHHHMHHHI:IHHMHMMHHHHHMHIHHHHIHI;\n"
		"     ;HHHHHHHHMMHMMMMMHMHHMMHIHMI:IIHHHMHHHHMHMHIHIHHHHI:.\n"
		"     IHHHHHHHHHHMHMMMMMHMHHMMHHMMII:IHHMMHMHHHHMMHMHMHHHH;\n"
		"     ;HH:\":IHHHHMHMMMMMHMHIHMHIIMMHI:IMHMMMI:HHHHHMMHHHHI:I.\n"
		"    ;HV\" . .:IIHHHMMMMMMMHHHMMHIIHMHHI:HHHMHI:IHHIHHIHHMHI:II;.\n"
		"   ;IV\"   . .''\":VMMMMMMHMHHHMMHI:HHHHI:HHHIHI:IHHHHHIHHHIHII;,\n"
		"   .II\"   .. .  ':VHHHMHMMMMMHMHHI:HMMHI:IHHHI::IHHHI:HIHHHI:I:.\n"
		"  .II . . .  . .  ':HHHHMHMMMHMMMHIHIMMMHI:HHHMI:IHHHIHI:HHHHII:I.\n"
		" .;V' . .. .  .    'IHMMMHHMHHHMMMHIHIHHHHI:IHHHI:IHHHHHIHHHHHIIHII:.\n"
		".:I\" .. . .    .   :IHMMMHHHMHHIHHHI:HHIHHHIHIHHHAIHHHHHHI:HHHIHII:.\n"
		"'..:  .  .       .  :IMMMHMHHIMHIIHHI:IHHI:IHHIHHHHIHIHHHHIHIHHHHIHI:.\n"
		".: .. . . .      ..:IHMMMHMHMHMHHHHMHIHHI:.IVIIHHHIHHHHHHHHI:HIHHIHII:.\n"
		".: .   . .        . :IHMMMHMIHIH:IIHHHIHH:.I:IIHHHIHHHHHHHHIHI:IHHHI:;.\n"
		":: .:. .  .   .   ..:IHHMMMHMIHIH:IIHHHMHH::..:HHHHI:HHHHHHI:I:IIIHII;\n"
		":. ... . .  .     ..::HHHMMHMHHII:HIIHHMMHH:..:HHHMHHIHHHI:: . :IHII:I\n"
		"':....   . .      . ..:IHHHMMMMHMHI:HIHMMMHA...VHMMHHHMI:'  .' :IH::\"\n"
		" :. ..  ....    .    ..IHHHHMMMMHHII:I:IHMMHA. .VHMHHHI:' ''    '':,\n"
		" ::...  . .... .   . ..::IHHHMMMMIHII::I:IHMMHHMHIHIHI''   .  .     ,\n"
		" ::.... . .....  ..  ...::IIIHHHMMIHI::IHHHIIIHHHIIHI\".  ..   .      ,\n"
		" ::.:.......... .. . ....:::HHIIHHHHHHHIIHMMMHI:' 'VI::..  . .        ,\n"
		" ::.:............. .. . ...AHIHIIIIIHHHI::\"\"'      'VII:.. ..    .\n"
		" ::.:.:.......... .. .  ...HHHIIIIIIHHHI::. .       'VII::. . .       ,\n"
		" ':::.:.:..... .. . . . ..:MHHIHIIIII:I::. .         'VII:::. ..      .\n"
		"  :::::.:..:.... . . . ...AHHHHIHIIII:::. .           'VII:::. . .   :.\n"
		"  :::::::.:..... .. . ....MHHHHHIHIII::.:.. .          'VII::.  .   ::\n"
		"  :::::::::.:.... .. ....:MHHHHIHII:I::::...  .         'VI::. .   ::I)\n"
		"  '::::::::::.:... .. ...:MHHHHIHIIII::::..  .           'VI:.    ...:V\n"
		"   .:::::::::::.:.... . .AMMHHIHIII:I::::...  .  .        I::.   ...:-\"\n"
		"   :.::I::::::::.:. .  ..MMMHHIHIIII:I:::... .  .        .::.  ,..-\"\n"
		"   :..:II:I:::::.:.. . ..MMMHHIHIIIIIII:I::.... .  .    ..::\"\"'\n"
		"  .::.:III:I::::::.:.. ..MMMMIVHIHIIIII:I::::.... .   .....:,\n"
		".:.::..:III:I:::::.:... .MMHMAIVHHIHIIIII:I::::.. .  ..::..:,\n"
		". .:::.::III:I::::.:... .VMMHMAIVHHHIHIIII:I::::..  ..:...:::\n"
		". :::I.:::III:I:::.::.. .:MMHHMAIVHHIHIIIII:I::::....:::.::::\n"
		" .::IIH.:::III:I::::.:.. .MMHMHMAIVHHHIHIIIIII:I:::.:::::::I)\n"
		".::IIHH.II:::II:I::::.:...MMMHMHMAIVHHHHHIHII:I:::..::::::HV\n"
		"::IIIHIH.III::I:I::::.:. .MHHMHHHIAIIVHHHHIHIII:...::::.:-\"\n"
		":IIHIHHA.VIHII:I:::::::...HHHHHHIHI::\":VHHHII:I:::...:-'\n"
		"IIHIHHHHI.HHIHII:I:::::...HHHIHII:' .  .'\"VIIIII::-'\n"
		"IHIHHHHH-:HHIHIIII:I::.:..HIHI::. ..  ...:\"\n"
		"HIHHHHIHHH:HHHIHIIII:I::.:HII:'. .   ..:\"\n"
		"HHHHHHMHHHIHHHHHHIHIII::.IHI:.  .    ..:-.,\n"
		"HHHHHHHMHHIHHHHHHHIHII:..II:'  .    .:\"    ''\"-.\n"
		"HHHHHHHMHHIHHHHHHIHII::..I;'. .   ..:\"          '\"-.\n"
		"HHHHHHHMHIHHHHHHHHIHI::,.I;' . .   .;\"          \"- . \",\n"
		"MMHMHHHHHH-IHHHHHHIHII::.::;.   :.:;.... .             '\"-.\n"
		"MMMHMHHHHHHIHHHHHHIHII::..:.,  .N.:I::.... .               '\"-.\n"
		"MMMMHMHHHHHIHHHHHHIHIII:..:.;. :.:AI:::..... .  .             .'-.\n"
		"MMMMMHMHHHIHHHHHHHHHIHII:..:.;:.:AIII::::....... .               .':,\n"
		"MMMMHMHHHHIHHHHHHHHHHIH:I:.:.,::AHIHIII:I::::::::...... .    .  ...::,\n"
		"MMMHMHHHHHIHVHHHHHHHHHIII::.:.:AHHIHIHIIIII:I:::::::.:....... .. ...::.\n"
		"MHMHHHIHIIII:HHHHHHHIHII:I:. :AHHHHHHHHHHHIHIIHIIIIIII:I::.:..... ..::.\n"
		"HHHHIHIIII:I:HHHHHHHHIHII:: .IHHHHHHHHHHHHHHHHHHHHIIHIII:I::::::::::::.\n"
		"HHIHIIIII:I::VHHHHHHHIHII::. :MHHHHHHHHHHHHHHHHHHHHHHIHIIHIIIIIIIIIIIV\n"
		"HHIHIIII:I::::MHHHHHHHIII::.. MMMMMMMMMMMMMMMMMMMMHMHHHHHHIIHIIIHIIIV'\n"
		"HHHIHII:I::I::MHHHHHHIHIII:: .HHIHHHHHIHHHHHHHHIHHIHHHIHHHHIHHIHIHHV'\n"
		"HHHHIHII:I::::HHHHHHHIHII:I:. MHHHIHHHHHHHIHHHHHHIHHHHHHHIHHHHHHHHV'\n"
		"MMHHHIHIII:I::HHHHHHHHIHIII: .:MMMMMMMMMMMMMHMHHHHHHHHHHHHHHHHHV:'\n"
		"II:IHMHHI::::AIHHHHHHHHHIII::. MMMMMMMMMMMMMMMMMMMMMHMHHHHHHHV:'\n"
		"III:IHMHIAMMMIHHHHHHHHHIHII....MMMMMMMMMMMMMMMMM--\"\"\"''\n"
		"IIIII:I:IIHMMMMMHHHHHHHHHHHII:::\"\"\"\"\"\"\"\"\"\"\"\"\"''\n"
		"IIIII:I:II:.T,  'VHHHHHHHHIHI:::\n"
		"IIIHIII:I:::.:,  :HHHHHHHHHHIHII\n"
		"IIIIII:I::::::.,  VHHHHHHHHHHIHI\n"
		"IIHII:I::::.:..., 'MMMHMHHHHHIHI.\n"
		"IIII:I:::::.:....:.VMMMHMHHHHHIH.\n"
		"IIIIII:I::::::.:..:.MMMMMHMHHHHH:\n"
		"IHIIIIII:II::::.:.:.VMMMMMHMHHHHA.\n"
		"IIIHIIIHIII:I::::.:..VMMMMMHMHHHHA\n"
		"IIIIIHIIIIIII:I:::.:..VMMMMHMMHHHH.\n"
		"IIHIIIIIIHIIIII:I:::..IMMMMMMMHMHHI\n"
		"HIIIIIHIIIIIIIII:I:.:..VMMMMMHMHHI:.\n"
		"HIHIIIIHIIIIIHIHI:I::..IMMMMHMHIHI:.\n"
		"HHIHIIIIIIHIIIIHIHIII:.:MMMMMHMHHI::\n"
		"HHHIHHHHHHIIIIIIHHHHIHI:MMMMMHMHHII:\n"
		"HHHHIHIIIHIIIIHIHHHHHHHI..HHHIHIIHI:.\n"
		"HHHHHHIHIIIIIIIIIHIHH..IHHHHIHI:III:,\n"
		"HMHHHHHIHIIIIIIIIIHIHMHHIIHIIHI:II:::,\n"
		"MMHHHHHHHHIHIIIIIIIHMIHIIHHIIIHI:I::..,\n"
		"MHMHMHHHHHHHHHIHIIH.;I:IIIHHIIHHI:::::.,\n"
		"MMMMMHMHHHHHHHHIHIH;I:IHIHII:HI:HII::.::.\n"
		"MMMMMMMMHMHHHHHHHIH;I:IHMHI.:HIIHI:II:IHA\n"
		"HMMMMMMMMMHMHHHHHHVI::IMHIHHHMH:IH::I:IHH.\n"
		"HHHMMMMMMMMMMHMHH;I:HHIMHHHHMHHIHHI.:AMHI:\n"
		"HHHHMMMHHHHMMMMM;I:IIHHIIHAIIIHI:HI:HA:IHI\n"
		"HIHHHHMMMHHHMMM:II:IMHHIIMIHIIIHIHHIHMMH.I"
	};
}